PodHealthCheck:
    alert: ZDB-Redis-PodHealthCheck-${serviceName}-redis-${role}
    expr: absent(mysql_up{service="${serviceName}-redis${exprRole}"}) == 1
    for: 1m          
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: 'Redis의 Pod 동작하지 않습니다. (서비스: {{ $labels.service }})'
      summary: 'Pod 동작 중단'
ContainerHealthCheck:
    alert: ZDB-Redis-ContainerHealthCheck-${serviceName}-redis-${role}
    expr: kube_pod_container_status_ready{pod="${serviceName}-redis${exprRole}", container="redis"} == 0
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: 'Redis 컨테이너의 동작이 중단되었습니다. (서비스: {{ $labels.pod }})'
      summary: 'Redis 컨테이너 동작 중단'
DBHealthCheck:
    alert: ZDB-Redis-DBHealthCheck-${serviceName}-redis-${role}
    expr: mysql_up{service="${serviceName}-redis${exprRole}"} == 0
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: 'Redis의 동작이 중단되었습니다. (서비스: {{ $labels.service }})'
      summary: 'Redis 동작 중단'
CPUUsage:
    alert: ZDB-Redis-CPUUsage-${serviceName}-redis-${role}
    expr: (sum(rate(container_cpu_usage_seconds_total{pod_name="${serviceName}-redis${exprRole}", container_name="redis"}[1m])) by (pod_name, container_name)) / ((sum(container_spec_cpu_quota{pod_name="${serviceName}-redis${exprRole}", container_name="redis"}) by (pod_name, container_name)) / 100000) * 100 > ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: 'CPU 사용량이 임계치를 초과하였습니다. (서비스: {{ $labels.pod_name }}, 임계값: 80%, 현재값: {{ $value }}%)'
      summary: 'CPU 사용량 임계치 초과'
MemoryUsage:
    alert: ZDB-Redis-MemoryUsage-${serviceName}-redis-${role}
    expr: (sum(container_memory_working_set_bytes{pod_name="${serviceName}-redis${exprRole}", container_name="redis"}) by (pod_name, container_name)) / (sum (container_spec_memory_limit_bytes{pod_name="${serviceName}-redis${exprRole}", container_name="redis"}) by (pod_name, container_name)) * 100 > ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: '메모리 사용량이 임계치를 초과하였습니다. (서비스: {{ $labels.pod_name }}, 임계값: 95%, 현재값: {{ $value }}%)'
      summary: '메모리 사용량 임계치 초과'
Connections:
    alert: ZDB-Redis-Connections-${serviceName}-redis-${role}
    expr: (mysql_global_status_threads_connected{service="${serviceName}-redis${exprRole}"} / mysql_global_variables_max_connections{service="${serviceName}-redis${exprRole}"} * 100) > ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: 'Redis의 Connnections값이 임계치를 초과하였습니다. (서비스: {{ $labels.service }}, 임계값: 80%, 현재값: {{ $value }}%)'
      summary: 'Connections 임계치 초과'
SlowQueries:
    alert: ZDB-Redis-SlowQueries-${serviceName}-redis-${role}
    expr: rate(mysql_global_status_slow_queries{service="${serviceName}-redis${exprRole}"}[2m]) > ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: 'Redis의 Slow Query가 발생했습니다. (서비스: {{ $labels.service }})'
      summary: 'Redis Slow Queries'
ReplicationStatus:
    alert: ZDB-Redis-ReplicationStatus-${serviceName}-redis-slave
    expr: mysql_slave_status_slave_sql_running{service="${serviceName}-redis-slave"} == 0 OR mysql_slave_status_slave_io_running{service="${serviceName}-redis-slave"} == 0
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: 'Redis의 Replication이 정상적으로 수행되지 않고 있습니다. (서비스: {{ $labels.service }})'
      summary: 'Replication 중단'
ReplicationDelay:
    alert: ZDB-Redis-ReplicationDelay-${serviceName}-redis-slave
    expr: mysql_slave_status_sql_delay{service="${serviceName}-redis-slave"} > ${value2}
    for: 5m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
      namespace: ${namespace}
      serviceName: ${serviceName}
    annotations:
      description: 'Redis의 Replication 수행 중 지연이 발생하였습니다. (서비스: {{ $labels.service }}, 지연: {{ $value }}초)'
      summary: 'Replication Delay' 