PodHealthCheck:
    condition: ==
    value: 1
    priority: P1
    for: 1m
ContainerHealthCheck:
    condition: == 
    value: 0
    priority: P1
    for: 1m
DBHealthCheck:
    condition: == 
    value: 0
    priority: P1
    for: 1m
CPUUsage:
    condition: '>'
    value: 80
    priority: P3
    for: 1m
MemoryUsage:
    condition: '>'
    value: 95
    priority: P3
    for: 1m
Connections:
    condition: '>'
    value: 80
    priority: P3
    for: 1m
SlowQueries:
    condition: '>'
    value: 0.1
    priority: P3
    for: 1m  
ReplicationStatus:
    condition: ==
    value: 0
    priority: P4
    for: 1m   
ReplicationDelay:
    condition: '>' 
    value: 0
    priority: P4
    for: 1m    