info:
  app:
    name: zdb-portal-server
    version: 1.0.0-SNAPSHOT
    description: zdb-portal-server

spring:
  profiles:
    active: local

management:
 security:
  enabled: false

---
spring:
  profiles: local
  datasource:
#    url: jdbc:mariadb://169.56.94.12:3306/zdb
    url: jdbc:mariadb://169.56.80.186:3306/zdb
    platform: h2
    username: zdb
    password: 1111
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true

logging:
  config: classpath:logback-local.xml

k8s:
  region: seo01
  cluster: zdb-dev
  privatelb: 10.178.191.134
  publiclb: 169.56.70.222
#  masterUrl: "https://169.56.69.242:23078"    
  masterUrl: "https://169.56.69.242:30134"    
  daemonUrl: "http://localhost:8090" 
  
chart:
  mariadb:
    url: "https://github.com/cnpst/zdb-chart-repo/raw/master/stable/mariadb/charts/mariadb-4.2.0.tgz"
  redis:
    url: "https://github.com/cnpst/zdb-chart-repo/raw/master/stable/redis/charts/redis-3.3.2.tgz"
  
iam:
    baseUrl: https://zcp-iam.cloudzcp.io:443
      
storage:
  storageType: AWS_S3
  accessKey: "6bf48d42eb304e1292f178bf69034f12"
  secretKey: "0c61052e1bd30002a96cc57c8589d7521efef440f0471873"
  endpointUrl: "s3-api.us-geo.objectstorage.softlayer.net"
  apiKey: "na"
  serviceInstanceId: "na"
  location: "us"

backup:
  backupShell: "/zdb/shell/backup_mariadb.sh"
  restoreShell: "/zdb/shell/restore_mariadb.sh"
  prepareShell: "/zdb/shell/dump_master.sh"
  masterInfo: "/zdb/shell/master_info.sh"
  filemeta: "/zdb/shell/parse_filemeta.sh"
  cleanShell: "/zdb/shell/clean.sh"
  workingDir: "C:\\zdb\\work"
  target: "slave"
  type: "public"
  redisDumpPath: "bitnami/redis/data"
  redisDumpFile: "dump.rdb"

---
spring:
  profiles: prod
  datasource:
    url: ${datasource.url}
    username: zdb
    password: 24cmdshvek!
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true  
        
logging:
  config: classpath:logback-prod.xml
          
k8s:
  region: seo01
  cluster: zdb-dev
  privatelb: 10.178.191.134
  publiclb: 169.56.70.222
  masterUrl: ${MASTER_URL}
  daemonUrl: ${DAEMON_URL}
  
chart:
  mariadb:
    url: ${chart.mariadb.url}
  redis:
    url: ${chart.redis.url}
      
iam:
    baseUrl: ${iam.baseUrl}
          
storage:
  storageType: AWS_S3
  accessKey: "6bf48d42eb304e1292f178bf69034f12"
  secretKey: "0c61052e1bd30002a96cc57c8589d7521efef440f0471873"
  endpointUrl: "s3-api.us-geo.objectstorage.softlayer.net"
  apiKey: "na"
  serviceInstanceId: "na"
  location: "us"
 
backup:
  backupShell: "/zdb/shell/backup_mariadb.sh"
  restoreShell: "/zdb/shell/restore_mariadb.sh"
  prepareShell: "/zdb/shell/dump_master.sh"
  masterInfo: "/zdb/shell/master_info.sh"
  filemeta: "/zdb/shell/parse_filemeta.sh"
  cleanShell: "/zdb/shell/clean.sh"
  workingDir: "/zdb/work"
  target: "slave"
  type: "public"
  redisDumpPath: "bitnami/redis/data"
  redisDumpFile: "dump.rdb"
 