info:
  app:
    name: zdb-portal-server
    version: 1.0.5-SNAPSHOT
    description: zdb-portal-server

spring:
  profiles:
    active: local

management:
 security:
  enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true

security:
  basic:
    enabled: false
          
---
spring:
  profiles: local
  datasource:
    url: jdbc:mariadb://169.56.174.21:3306/zdb
    username: zdb
    password: 24cmdshvek!
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true

logging:
  config: classpath:logback-local.xml

k8s:
  masterUrl: "https://169.56.69.242:20292"    
  daemonUrl: "http://localhost:8090" 
  
chart:
  mariadb:
    url: "https://github.com/cnpst/zdb-chart-repo/raw/master/stable/charts/mariadb-4.2.5.tgz"
  redis:
    url: "https://github.com/cnpst/zdb-chart-repo/raw/master/stable/charts/redis-3.6.5.tgz"
  
iam:
    baseUrl: https://cbt-internal-iam.cloudzcp.io:443
      
storage:
  storageType: AWS_S3
  accessKey: "6bf48d42eb304e1292f178bf69034f12"
  secretKey: "0c61052e1bd30002a96cc57c8589d7521efef440f0471873"
  endpointUrl: "s3-api.us-geo.objectstorage.softlayer.net"
  apiKey: "na"
  serviceInstanceId: "na"
  location: "us"

backup:
  backupShell: "/zdb/shell/backup_mariadb.sh"
  restoreShell: "/zdb/shell/restore_mariadb.sh"
  prepareShell: "/zdb/shell/dump_master.sh"
  masterInfo: "/zdb/shell/master_info.sh"
  filemeta: "/zdb/shell/parse_filemeta.sh"
  cleanShell: "/zdb/shell/clean.sh"
  workingDir: "C:\\zdb\\work"
  target: "slave"
  type: "public"
  redisDumpPath: "bitnami/redis/data"
  redisDumpFile: "dump.rdb"

---
spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://zdb-portal-db-mariadb.zdb-system:3306/zdb
    username: zdb
    password: 24cmdshvek!
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true  
        
logging:
  config: classpath:logback-prod.xml
          
k8s:
  masterUrl: ${cluster.master}
  daemonUrl: http://zdb-backup-agent-loadbalancer.zdb-system:8080
  
chart:
  mariadb:
    url: ${chart.mariadb.url}
    storageClass: ${storage.class:ibmc-block-silver}
  redis:
    url: ${chart.redis.url}
    storageClass: ${storage.class:ibmc-block-silver}
          
iam:
    baseUrl: http://zcp-iam.zcp-system
          
storage:
  storageType: AWS_S3
  accessKey: "${storage.accessKey}"
  secretKey: "${storage.secretKey}"
  endpointUrl: "s3-api.us-geo.objectstorage.service.networklayer.com"
  apiKey: "na"
  serviceInstanceId: "na"
  location: "us"
 
backup:
  backupShell: "/zdb/shell/backup_mariadb.sh"
  restoreShell: "/zdb/shell/restore_mariadb.sh"
  prepareShell: "/zdb/shell/dump_master.sh"
  masterInfo: "/zdb/shell/master_info.sh"
  filemeta: "/zdb/shell/parse_filemeta.sh"
  cleanShell: "/zdb/shell/clean.sh"
  workingDir: "/zdb/work"
  target: "slave"
  type: "public"
  redisDumpPath: "bitnami/redis/data"
  redisDumpFile: "dump.rdb"
 
