info:
  app:
    name: zdb-portal-server
    version: 1.0.0-SNAPSHOT
    description: zdb-portal-server

spring:
  profiles:
    active: local

management:
 security:
  enabled: false
  endpoints:
    enabled-by-default: true
    web:
      exposure:
        include: info, health, metrics
  endpoint:
    health:
      show-details: always
  metrics:
    enable:
      jvm: true
      
---
spring:
  profiles: local
  datasource:
#    url: jdbc:mariadb://169.56.94.12:3306/zdb
    url: jdbc:mariadb://169.56.80.186:3306/zdb
    username: zdb
    password: 1111
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true

logging:
  config: classpath:logback-local.xml

k8s:
#  masterUrl: "https://169.56.69.242:23078"    
  masterUrl: "https://169.56.69.242:30134"    
  daemonUrl: "http://zdb.daemon.sk.com:8080" 
  
chart:
  mariadb:
    url: "https://github.com/cnpst/zdb-chart-repo/raw/master/stable/mariadb/charts/mariadb-4.2.0.tgz"
  redis:
    url: "https://github.com/cnpst/zdb-chart-repo/raw/master/stable/redis/charts/redis-3.3.2.tgz"
  
iam:
    baseUrl: https://zcp-iam.cloudzcp.io:443

---
spring:
  profiles: prod
  datasource:
    url: ${datasource.url}
    username: zdb
    password: 1111
    driverClassName: org.mariadb.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: true
        format_sql: true  
        
logging:
  config: classpath:logback-prod.xml
          
k8s:
  masterUrl: ${MASTER_URL}
  daemonUrl: ${DAEMON_URL}
  
chart:
  mariadb:
    url: ${chart.mariadb.url}
  redis:
    url: ${chart.redis.url}
      
iam:
    baseUrl: ${iam.baseUrl}
  