apiVersion: v1
kind: ServiceAccount
metadata:
  name: zdb-system-account
  namespace: zdb-system

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: zdb-system-account
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: zdb-system-account
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: zdb-system-account
subjects:
- kind: ServiceAccount
  name: zdb-system-account
  namespace: zdb-system