apiVersion: v1
kind: ConfigMap
metadata:
  name: zdb-portal-server-config
  namespace: zdb-system
data:
  chart.mariadb.url: https://github.com/cnpst/zdb-chart-repo/raw/master/stable/mariadb/charts/mariadb-4.2.0.tgz
  chart.redis.url: https://github.com/cnpst/zdb-chart-repo/raw/master/stable/redis/charts/redis-3.6.3.tgz
  master.url: https://169.56.69.242:32124
  storage.class: ibmc-block-gold
  cluster: zcp-demo
  zdb.backup.agent.url: http://10.178.145.85:8080
  datasource.url: jdbc:mariadb://10.178.31.212:3306/zdb
  iam.baseUrl: https://zcp-iam.cloudzcp.io:443
  grafana.url: http://grafana-zdb.cloudzcp.io
  zdb.portal.server.url: http://api.jp-tok.containers.mybluemix.net
  zcp.access.token.url: https://keycloak.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/token
  zcp.client.secret: 0227b024-6483-4e96-827b-3bc4dd73637e
  zcp.redirect.url: http://zdb.cloudzcp.io/login
  zcp.user.auth.url: https://keycloak.cloudzcp.io/auth/realms/zcp/protocol/openid-connect/auth  
