ZDB-MariaDB-PodHealthCheck:
    alert: ZDB-MariaDB-PodHealthCheck-${serviceName}
    expr: absent(mysql_up{service="${serviceName}"}) ${condition} ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: 'MariaDB의 Pod 동작하지 않습니다. (서비스: {{ $labels.service }})'
      summary: 'Pod 동작 중단'
ZDB-MariaDB-ContainerHealthCheck:
    alert: ZDB-MariaDB-ContainerHealthCheck-${serviceName}
    expr: kube_pod_container_status_ready{pod=~"${serviceName}.*", container="mariadb"} ${condition} ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: 'MariaDB 컨테이너의 동작이 중단되었습니다. (서비스: {{ $labels.pod }})'
      summary: 'MariaDB 컨테이너 동작 중단'
ZDB-MariaDB-DBHealthCheck:
    alert: ZDB-MariaDB-DBHealthCheck-${serviceName}
    expr: mysql_up{service=~"${serviceName}.*"} ${condition} ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: 'MariaDB의 동작이 중단되었습니다. (서비스: {{ $labels.service }})'
      summary: 'MariaDB 동작 중단'
ZDB-MariaDB-CPUUsage:
    alert: ZDB-MariaDB-CPUUsage-${serviceName}
    expr: (sum(rate(container_cpu_usage_seconds_total{pod_name=~"${serviceName}.*", container_name="mariadb"}[1m])) by (pod_name, container_name)) / ((sum(container_spec_cpu_quota{pod_name=~"${serviceName}.*", container_name="mariadb"}) by (pod_name, container_name)) / 100000) * 100 ${condition} ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: 'CPU 사용량이 임계치를 초과하였습니다. (서비스: {{ $labels.pod_name }}, 임계값: 80%, 현재값: {{ $value }}%)'
      summary: 'CPU 사용량 임계치 초과'
ZDB-MariaDB-MemoryUsage:
    alert: ZDB-MariaDB-MemoryUsage-${serviceName}
    expr: (sum(container_memory_working_set_bytes{pod_name=~"${serviceName}.*", container_name="mariadb"}) by (pod_name, container_name)) / (sum (container_spec_memory_limit_bytes{pod_name=~"${serviceName}.*", container_name="mariadb"}) by (pod_name, container_name)) * 100 ${condition} ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: '메모리 사용량이 임계치를 초과하였습니다. (서비스: {{ $labels.pod_name }}, 임계값: 95%, 현재값: {{ $value }}%)'
      summary: '메모리 사용량 임계치 초과'
ZDB-MariaDB-Connections:
    alert: ZDB-MariaDB-Connections-${serviceName}
    expr: (mysql_global_status_threads_connected{service=~"${serviceName}.*"} / mysql_global_variables_max_connections{service=~"${serviceName}.*"} * 100) ${condition} ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: 'MariaDB의 Connnections값이 임계치를 초과하였습니다. (서비스: {{ $labels.service }}, 임계값: 80%, 현재값: {{ $value }}%)'
      summary: 'Connections 임계치 초과'
ZDB-MariaDB-SlowQueries:
    alert: ZDB-MariaDB-SlowQueries-${serviceName}
    expr: rate(mysql_global_status_slow_queries{service=~"${serviceName}.*"}[2m]) ${condition} ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: 'MariaDB의 Slow Query가 발생했습니다. (서비스: {{ $labels.service }})'
      summary: 'MariaDB Slow Queries'
ZDB-MariaDB-ReplicationStatus:
    alert: ZDB-MariaDB-ReplicationStatus-${serviceName}
    expr: mysql_slave_status_slave_sql_running{service="${serviceName}-slave"} ${condition} ${value2} OR mysql_slave_status_slave_io_running{service="${serviceName}-slave"} ${condition} ${value2}
    for: 1m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: 'MariaDB의 Replication이 정상적으로 수행되지 않고 있습니다. (서비스: {{ $labels.service }})'
      summary: 'Replication 중단'
ZDB-MariaDB-ReplicationDelay:
    alert: ZDB-MariaDB-ReplicationDelay-${serviceName}
    expr: mysql_slave_status_sql_delay{service="${serviceName}-slave"} ${condition} ${value2}
    for: 5m
    labels:
      channel: ${channel}
      severity: ${severity}
      product: zdb
      priority: ${priority}
    annotations:
      description: 'MariaDB의 Replication 수행 중 지연이 발생하였습니다. (서비스: {{ $labels.service }}, 지연: {{ $value }}초)'
      summary: 'Replication Delay' 