use zdb;

update request_event set type='SERVICE' where type is null and operation = '서비스 생성';
update request_event set type='PVC' where type is null and operation = '스토리지 생성';
update request_event set type='SERVICE' where type is null and operation = '업데이트';
update request_event set type='SERVICE' where type is null and operation = '서비스 삭제';
update request_event set type='SERVICE' where type is null and operation = 'READ';
update request_event set type='SERVICE' where type is null and operation = '서비스 재시작';
update request_event set type='SERVICE' where type is null and operation = 'Pod 재시작';
update request_event set type='SERVICE' where type is null and operation = '서비스 On';
update request_event set type='SERVICE' where type is null and operation = '서비스 Off';
update request_event set type='CHANGEOVER' where type is null and operation = '서비스 전환(Master To Slave)';
update request_event set type='CHANGEOVER' where type is null and operation = '서비스 전환(Slave To Master)';
update request_event set type='CHANGEOVER' where type is null and operation = '서비스 전환 상태';
update request_event set type='CHANGEOVER' where type is null and operation = '서비스 전환(Fail-Back : Slave To Master)';
update request_event set type='PROCESS' where type is null and operation = 'Pocess 조회';
update request_event set type='PROCESS' where type is null and operation = 'Process 종료';
update request_event set type='DATABASE' where type is null and operation = 'DB Status 조회';
update request_event set type='DATABASE' where type is null and operation = 'DB Connection 조회';
update request_event set type='DATABASE' where type is null and operation = 'DB Status Variables 조회';
update request_event set type='DATABASE' where type is null and operation = 'DB System Variables 조회';
update request_event set type='DATABASE' where type is null and operation = 'DB Variables 조회';
update request_event set type='DATABASE' where type is null and operation = 'DB Schema 조회';
update request_event set type='DATABASE' where type is null and operation = 'DB Variables 수정';
update request_event set type='NETWORK' where type is null and operation = 'Public Network 생성';
update request_event set type='NETWORK' where type is null and operation = 'Public Network 삭제';
update request_event set type='NETWORK' where type is null and operation = '포트 변경';
update request_event set type='AUTOFAILOVER' where type is null and operation = 'Auto Failover 설정';
update request_event set type='AUTOFAILOVER' where type is null and operation = 'Auto Failover 환경 등록';
update request_event set type='BACKUPDISK' where type is null and operation = '백업 디스크 추가';
update request_event set type='BACKUPDISK' where type is null and operation = '백업 디스크 제거';
update request_event set type='BACKUP' where type is null and operation = '백업 실행';
update request_event set type='BACKUP' where type is null and operation = '백업 요청';
update request_event set type='BACKUP' where type is null and operation = '전체 백업 요청';
update request_event set type='BACKUP' where type is null and operation = '증분 백업 요청';
update request_event set type='BACKUP' where type is null and operation = '백업 데이터 삭제';
update request_event set type='BACKUP' where type is null and operation = '백업 수행중지';
update request_event set type='BACKUPSCHEDULE' where type is null and operation = '스케줄 설정';
update request_event set type='RESTORE' where type is null and operation = '백업 데이터 복원';
update request_event set type='RESTORE' where type is null and operation = '백업 데이터 기반 마이그레이션';
update request_event set type='RESTORE' where type is null and operation = 'Slave DB 복원';
update request_event set type='USER' where type is null and operation = '사용자 생성';
update request_event set type='USER' where type is null and operation = '사용자 업데이트';
update request_event set type='USER' where type is null and operation = '사용자 삭제';
update request_event set type='USER' where type is null and operation = '사용자 권한 삭제';
update request_event set type='USER' where type is null and operation = 'DB Privileges 조회';
update request_event set type='DATABASE' where type is null and operation = '데이터베이스 생성';
update request_event set type='DATABASE' where type is null and operation = '데이터베이스 삭제';
update request_event set type='TAG' where type is null and operation = '태그 추가';
update request_event set type='TAG' where type is null and operation = '태그 삭제';
update request_event set type='SCALE' where type is null and operation = '스케일 업';
update request_event set type='SCALE' where type is null and operation = '스토리지 스케일 업';
update request_event set type='SCALE' where type is null and operation = '스케일 아웃';
update request_event set type='WORKERPOOL' where type is null and operation = 'Node Worker Pools 조회';
update request_event set type='WORKERPOOL' where type is null and operation = 'Node Worker Pool 변경';
update request_event set type='WORKERPOOL' where type is null and operation = 'ZDB Worker Pool 변경';
update request_event set type='LOG' where type is null and operation = 'Slowlog Rotation';
update request_event set type='GLOBALCONFIG' where type is null and operation = 'Global 환경설정 생성';
update request_event set type='CONFIG' where type is null and operation = '환경설정 변경';
update request_event set type='CREADENTIAL' where type is null and operation = '비밀번호 변경';

 
update schedule_entity set throttle_yn = 'N', noti_yn = 'N';

update schedule_entity set schedule_type = 'DAILY', schedule_day = 0 where schedule_type is null;
commit;