## Bitnami MariaDB image
## ref: https://hub.docker.com/r/bitnami/mariadb/tags/
##
service:
  ## Kubernetes service type
  type: LoadBalancer
  port: 3306
  publicip:
    enabled: true

rootUser:
  ## MariaDB admin password
  password: zdbroot!@34
  forcePassword: false

db:
  ## MariaDB username and password
  user: zdb
  password: 24cmdshvek!
  name: zdb
  forcePassword: false

replication:
  enabled: true
  user: replicator
  password: zdbroot!@34
  forcePassword: false

master:
  antiAffinity: soft
  persistence:
    enabled: true
    storageClass: "ibmc-block-silver"
    annotations:
    accessModes:
    - ReadWriteOnce
    size: 20Gi

  ## Configure MySQL with a custom my.cnf file
  ## ref: https://mysql.com/kb/en/mysql/configuring-mysql-with-mycnf/#example-of-configuration-file
  ##
  config: |-
    [mysqld]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    basedir=/opt/bitnami/mariadb
    datadir=/opt/bitnami/mariadb/data
    tmpdir=/opt/bitnami/mariadb/tmp    
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid

    local_infile=0
    wait_timeout=3600
    interactive_timeout=3600
    
    query_cache_size=0
    query_cache_type=0
    query_cache_limit=0
    
    character-set-client-handshake=FALSE
    character_set_server=UTF8
    collation-server=utf8_general_ci
    
    # Common Config
    back_log=200
    join_buffer_size=64k
    max_allowed_packet=16M
    max_heap_table_size=16M
    max_connection=200
    performance_schema
    read_buffer_size=1M
    read_rnd_buffer_size=1M
    skip-external-locking
    skip-name-resolve=1
    sort_buffer_size=64k
    max_length_for_sort_data=1024
    tmp_table_size=64M
    
    binlog_cache_size=1M
    table_open_cache=4000
    open_files_limit=8192
    transaction-isolation=READ-COMMITTED
    
    # Log Config
    log_error=/bitnami/mariadb/logs/mysqld.log
    slow_query_log_file=/bitnami/mariadb/logs/maria_slow.log
    slow_query_log=1
    long_query_time=5
    
    # Innodb Config
    innodb_buffer_pool_size=256M
    innodb_file_per_table=1
    innodb_flush_method=O_DIRECT
    innodb_lock_wait_timeout=15
    innodb_log_buffer_size=10M
    innodb_log_file_size=100M 
    innodb_log_files_in_group=4
    innodb_thread_sleep_delay=0
    innodb_fast_shutdown
    innodb_thread_concurrency=0
    innodb_read_io_threads=4
    innodb_write_io_threads=8
    innodb_autoinc_lock_mode=1
    innodb_open_files=8192
    innodb_buffer_pool_instances=4
    innodb_lru_scan_depth=512
    innodb_sort_buffer_size=4M
    
    # MyISAM Config
    bulk_insert_buffer_size=16M
    key_buffer_size=16M
    myisam_max_sort_file_size=1G
    myisam_repair_threads=1
    myisam_sort_buffer_size=16M
    myisam_recover_options=BACKUP,QUICK
    
    # Replication related settings
    expire_logs_days=1
    max_binlog_size=200M
    sync_binlog=1
    binlog_format=ROW
    log_bin_trust_function_creators=1
    
    # Thread Pool
    thread_handling=pool-of-threads
    thread_pool_stall_limit=60
    thread_pool_idle_timeout=120
   
    default-time-zone=+09:00

    [mysql]
    no-auto-rehash
    max_allowed_packet=16M
    
    [mysqld_safe]
    log_error=/bitnami/mariadb/logs/mysqld_safe.log
    
    [mysqldump]
    quick
    max_allowed_packet=16M
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

  ## Configure master resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: private
    
slave:
  replicas: 1
  antiAffinity: soft
  persistence:
    enabled: true
    storageClass: "ibmc-block-silver"
    annotations:
    accessModes:
    - ReadWriteOnce
    size: 20Gi

  ## Configure MySQL slave with a custom my.cnf file
  ## ref: https://mysql.com/kb/en/mysql/configuring-mysql-with-mycnf/#example-of-configuration-file
  ##
  config: |-
    [mysqld]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    basedir=/opt/bitnami/mariadb
    datadir=/opt/bitnami/mariadb/data
    tmpdir=/opt/bitnami/mariadb/tmp    
    pid-file=/opt/bitnami/mariadb/tmp/mysqld.pid
    
    local_infile=0
    wait_timeout=3600
    interactive_timeout=3600
    
    query_cache_size=0
    query_cache_type=0
    query_cache_limit=0
    
    character-set-client-handshake=FALSE
    character_set_server=UTF8
    collation-server=utf8_general_ci
    
    # Common Config
    back_log=200
    join_buffer_size=64k
    max_allowed_packet=16M
    max_heap_table_size=16M
    max_connection=200
    performance_schema
    read_buffer_size=1M
    read_rnd_buffer_size=1M
    skip-external-locking
    skip-name-resolve=1
    sort_buffer_size=64k
    max_length_for_sort_data=1024
    tmp_table_size=64M
    
    binlog_cache_size=1M
    table_open_cache=4000
    open_files_limit=8192
    transaction-isolation=READ-COMMITTED
    
    # Log Config
    log_error=/bitnami/mariadb/logs/mysqld.log
    slow_query_log_file=/bitnami/mariadb/logs/maria_slow.log
    slow_query_log=1
    long_query_time=5
    
    # Innodb Config
    innodb_buffer_pool_size=256M
    innodb_file_per_table=1
    innodb_flush_method=O_DIRECT
    innodb_lock_wait_timeout=15
    innodb_log_buffer_size=10M
    innodb_log_file_size=100M 
    innodb_log_files_in_group=4
    innodb_thread_sleep_delay=0
    innodb_fast_shutdown
    innodb_thread_concurrency=0
    innodb_read_io_threads=4
    innodb_write_io_threads=8
    innodb_autoinc_lock_mode=1
    innodb_open_files=8192
    innodb_buffer_pool_instances=4
    innodb_lru_scan_depth=512
    innodb_sort_buffer_size=4M
    
    # MyISAM Config
    bulk_insert_buffer_size=16M
    key_buffer_size=16M
    myisam_max_sort_file_size=1G
    myisam_repair_threads=1
    myisam_sort_buffer_size=16M
    myisam_recover_options=BACKUP,QUICK
    
    # Replication related settings
    expire_logs_days=1
    max_binlog_size=200M
    sync_binlog=1
    binlog_format=ROW
    log_bin_trust_function_creators=1
    
    # Thread Pool
    thread_handling=pool-of-threads
    thread_pool_stall_limit=60
    thread_pool_idle_timeout=120
    
    default-time-zone=+09:00
    
    [mysql]
    no-auto-rehash
    max_allowed_packet=16M
    
    [mysqld_safe]
    log_error=/bitnami/mariadb/logs/mysqld_safe.log
    
    [mysqldump]
    quick
    max_allowed_packet=16M
    
    [client]
    port=3306
    socket=/opt/bitnami/mariadb/tmp/mysql.sock
    default-character-set=UTF8

  ##
  ## Configure slave resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  ##
  resources:
    requests:
      cpu: 500m
      memory: 512Gi
    limits:
      cpu: 500m
      memory: 512Gi
  annotations:
    service.kubernetes.io/ibm-load-balancer-cloud-provider-ip-type: private
    
metrics:
  enabled: true
  image:
    registry: docker.io
    repository: prom/mysqld-exporter
    tag: v0.10.0
    pullPolicy: IfNotPresent
  resources: {}
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9104"
